### ISSUE TITLE
Latest version tag missing 'v'

### ISSUE THREAD

**Issue by skoonin** [olegtarasov/get-tag#294]
Hello! 

This workflow broke for me today when I updated it. I realized it was because I updated it to `v2.1.3`, but your latest tag is just `2.1.3`.  

When you have time, can you please create a new release tag to match github actions patterns and your old tags? 

Thank you for you work on this!

**Comment by dfeldick** [comment]
Same issue for me.

**Comment by olegtarasov** [comment]
@skoonin @dfeldick Hi! Thanks for catching this, I pushed `v2.1.3` and updated the marketplace.
