### ISSUE TITLE
GITHUB_TAG_NAME is an invalid env var name

### ISSUE THREAD

**Issue by jasonkarns** [olegtarasov/get-tag#3]
The github actions docs indicate that the `GITHUB_` prefix for env vars is reserved.

https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#naming-conventions

> Note: GitHub reserves the GITHUB_ environment variable prefix for internal use by GitHub. Setting an environment variable or secret with the GITHUB_ prefix will result in an error.

**Comment by olegtarasov** [comment]
@jasonkarns Hi Jason! I finally pushed v2 of this action, which now uses `GIT_TAG_NAME` instead of `GITHUB_TAG_NAME`.
