### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by brechtm** [olegtarasov/get-tag#302]
GitHub outputs a deprecation warning about _set-output_, so this will break soon.

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by olegtarasov** [comment]
Hi @brechtm! I've just pushed `v2.1.4` that should solve this issue.
