### ISSUE TITLE
feature request: option to strip leading `v`

### ISSUE THREAD

**Issue by jasonkarns** [olegtarasov/get-tag#4]
It's pretty common for git tags to have a leading `v` prefix on the version number. However, it's equally common (and in the case of needing this very action, I'd say exceedingly likely) that one may need or prefer the version name _without_ the leading v.

It would be great if there were an option (default to whatever makes sense to you) that would automatically strip any leading `v` when returning the tag name.

**Comment by olegtarasov** [comment]
@jasonkarns Hi Jason! I've just pushed v2 of this action, and it now supports extracting pieces of tag string using regex.
